# -*- coding: utf-8 -*-
"""Strategic Sales Analysis & Time-Series Forecasting Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STDptFwte4_Dy9hxWBZjTqZWtG8Kqg-C

```
# Connect the Google drive
```
"""

from google.colab import drive
drive.mount('/content/drive')

"""Import CSV file"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Global_Superstore2.csv",
                 encoding="latin1")

df.head()

df.info()

df.describe()

# Convert to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True, errors='coerce')

df.head()

df.info()

# Remove duplicates
df.drop_duplicates(inplace=True)

# Check missing values
print(df.isnull().sum())

# Missing value on postal code
df.drop(columns=['Postal Code'], inplace=True)

df.info()

# ship date object to datetime
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True, errors='coerce')

df.info()

"""KPI Calculations"""

# KPI CALCULATIONS

total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
average_discount = df['Discount'].mean()
total_quantity = df['Quantity'].sum()
average_shipping_cost = df['Shipping Cost'].mean()
total_orders = df['Order ID'].nunique()

# Display KPI results
print("----- KPI RESULTS -----")
print(f"Total Sales: {total_sales:,.2f}")
print(f"Total Profit: {total_profit:,.2f}")
print(f"Average Discount: {average_discount:.2%}")
print(f"Total Quantity Sold: {total_quantity}")
print(f"Average Shipping Cost: {average_shipping_cost:.2f}")
print(f"Total Unique Orders: {total_orders}")

# Sales by Category
print("\n--- Sales by Category ---")
print(df.groupby('Category')['Sales'].sum())

# Sales by Region
print("\n--- Sales by Region ---")
print(df.groupby('Region')['Sales'].sum())

# Monthly Sales Trend
monthly_sales = df.resample('M', on='Order Date')['Sales'].sum()
print("\n--- Monthly Sales Trend ---")
print(monthly_sales.head())

"""1) Sales by Category — Bar Chart"""

import matplotlib.pyplot as plt

df.groupby('Category')['Sales'].sum().plot(kind='bar')
plt.title('Sales by Category')
plt.xlabel('Category')
plt.ylabel('Total Sales')
plt.show()

"""2) Monthly Sales Trend — Line Graph"""

monthly_sales.plot(kind='line')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.show()

"""3) Sales by Region — Pie Chart"""

df.groupby('Region')['Sales'].sum().plot(kind='pie', autopct='%1.1f%%')
plt.title('Sales by Region')
plt.ylabel('')
plt.show()

"""4) Profit vs Discount — Scatter Chart"""

df.plot(kind='scatter', x='Discount', y='Profit')
plt.title('Discount vs Profit')
plt.show()

"""Now Lets start with Developing **forecasting time series data** that exhibits strong seasonal effects (like monthly or yearly cycles) and holiday effects (like major sales days or public holidays)"""

# Install Libraries
!pip install prophet

# Import all necessary libraries
import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt
import numpy as np
import warnings
warnings.filterwarnings('ignore') # Suppress warnings for cleaner output

# Set plot style
plt.style.use('ggplot')

# Initial Data Check
print("Initial DataFrame Information:")
print(df.info())
print("\nFirst 5 Rows:")
print(df.head())

"""1. Data Preparation and Feature Engineering (The Final Dataset)"""

# ======================================================================
# DATA PREPARATION AND REGRESSOR ENGINEERING
# Purpose: Transform transactional data into the monthly time-series
#          format required for Prophet (ds, y) and create features
#          (regressors) for advanced modeling.
# ======================================================================

# 1. Date Cleaning
# ***Adjust 'Order Date' to the actual date column name in your data***
df['Order Date'] = pd.to_datetime(df['Order Date'])

# 2. Aggregate Sales (y) and Regressors
# 'MS' stands for Month Start frequency
monthly_data = df.set_index('Order Date').resample('MS').agg(
    # Target Variable: Sum of Sales
    y=('Sales', 'sum'),
    # Regressor 1: Sum of Shipping Cost
    total_shipping_cost=('Shipping Cost', 'sum'),
    # Regressor 2: Average of Discount
    avg_discount=('Discount', 'mean')
).reset_index()

# 3. Rename columns to the required Prophet format
monthly_data.columns = ['ds', 'y', 'total_shipping_cost', 'avg_discount']

# 4. Check Final Data Structure
print("Final Time Series Data Structure:")
print(monthly_data.head())

# 5. Store Regressor Means (Needed to forecast future periods)
MEAN_SHIPPING = monthly_data['total_shipping_cost'].mean()
MEAN_DISCOUNT = monthly_data['avg_discount'].mean()
print(f"\nMean Shipping Cost: {MEAN_SHIPPING:.2f}")
print(f"Mean Average Discount: {MEAN_DISCOUNT:.4f}")

"""2. Baseline Model: Time-Only (Establishing the Benchark)"""

# ======================================================================
# BASELINE MODEL (TIME-ONLY)
# Purpose: Establish the baseline accuracy MAPE using only
#          time and seasonality features for comparison.
# ======================================================================

# 1. Initialize Baseline Model
model_baseline = Prophet(
    growth='linear',
    seasonality_mode='multiplicative',
    yearly_seasonality=True
)

# 2. Fit and Establish Baseline
model_baseline.fit(monthly_data[['ds', 'y']])

# 3. Run Cross-Validation to get the official 1-year MAPE
# Parameters for 4-year data: Initial 2 years, Horizon 1 year
two_years_days = 2 * 365
six_months_days = 6 * 30.5
one_year_days = 1 * 365

print("Starting Cross-Validation for Baseline Model...")
df_cv_base = cross_validation(
    model_baseline,
    initial=f'{two_years_days} days',
    period=f'{six_months_days} days',
    horizon=f'{one_year_days} days'
)

df_p_base = performance_metrics(df_cv_base)
BASELINE_MAPE = df_p_base['mape'].mean() * 100

print(f"\nBASELINE RESULT (Time Only): {BASELINE_MAPE:.2f}% MAPE")

"""3. Final Model: With Regressors (Better Solution)"""

# ======================================================================
# CODE CELL 4: FINAL REGRESSOR MODEL
# Purpose: Add Discount and Shipping Cost as external regressors to
#          significantly improve predictive accuracy.
# ======================================================================

# 1. Initialize the Final Model
model_reg = Prophet(
    growth='linear',
    seasonality_mode='multiplicative',
    yearly_seasonality=True
)

# 2. ADD EXTERNAL REGRESSORS (The mind-blowing part)
model_reg.add_regressor('total_shipping_cost')
model_reg.add_regressor('avg_discount')

# 3. Fit the model to the data WITH regressors
print("\nFitting FINAL Prophet model with regressors...")
model_reg.fit(monthly_data)
print("Final Model training complete.")

"""4. Final Validation and Actionable Forecast"""

# ======================================================================
# FINAL VALIDATION AND FORECAST PLOT
# Purpose: Confirm the superior accuracy and generate the final plot.
# ======================================================================

# 1. Run Cross-Validation for the Regressor Model
print("Starting Cross-Validation for REGRESSOR Model...")
df_cv_reg = cross_validation(
    model_reg,
    initial=f'{two_years_days} days',
    period=f'{six_months_days} days',
    horizon=f'{one_year_days} days'
)

df_p_reg = performance_metrics(df_cv_reg)
FINAL_MAPE = df_p_reg['mape'].mean() * 100

# 2. Print Final Comparison
print("\n--- FINAL MODEL ACCURACY COMPARISON (1-Year Forecast) ---")
print(f"BASELINE Model (Time Only): {BASELINE_MAPE:.2f}% MAPE")
print(f"FINAL Model (Time + Regressors): {FINAL_MAPE:.2f}% MAPE")
print(f"✅ IMPROVEMENT: {BASELINE_MAPE - FINAL_MAPE:.2f} percentage points.")


# 3. Generate Future Dates (12 months)
future = model_reg.make_future_dataframe(periods=12, freq='MS')

# 4. Add Future Regressor Values
# For future periods, we use the historical mean (calculated in Step 2)
future['total_shipping_cost'] = MEAN_SHIPPING
future['avg_discount'] = MEAN_DISCOUNT

# 5. Make Final Prediction
forecast = model_reg.predict(future)

# 6. Plot the Final Forecast
fig = model_reg.plot(forecast)
plt.title(f'Highly Accurate Sales Revenue Forecast (MAPE: {FINAL_MAPE:.2f}%)')
plt.xlabel('Date')
plt.ylabel('Sales Revenue')
plt.show()


# [Image of Time Series Forecasting Plot with Confidence Intervals]


# Display the actionable forecast table
print("\nActionable Revenue Forecast for Next 12 Months:")
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(12).round(0)